"""Fail-closed CASE-TESTY signed-authoring control plane.

Validation is secret-free. Publication is bounded to one synthetic operation,
one repository, one base revision, one target branch and one file allowlist.
This module never writes directly to main and never merges pull requests.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import re
import subprocess
import urllib.parse
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from factory.github_actions_client import (
    GitHubActionsClient,
    GitHubActionsError,
)
from factory.quality.case_signed_authoring import (
    ALLOWED_PATHS,
    MAIN_BRANCH,
    OPERATION,
    TARGET_BRANCH,
    render_regression_suite_update,
    render_test_file,
)

MANIFEST_SCHEMA = "lukart.signed-authoring-manifest.v1"
RECEIPT_SCHEMA = "lukart.signed-authoring-receipt.v1"

SOURCE_PATH = "factory/quality/case_regression_suite.py"
TEST_PATH = (
    "tests/case/"
    "test_case_regression_suite_manual_inventory.py"
)

PR_TITLE = (
    "case-testy: validate manual product smoke inventory"
)

PR_BODY = """Closes #295

Generated by the hardened CASE-TESTY signed-authoring path.

- validates canonical manual/product-smoke structure
- preserves CASE-BATCH execution semantics
- preserves manual_product_smoke=SKIPPED
- synthetic-only scope
- no automatic merge
"""

_SECRET_ENV_KEYS = {
    "LUKART_ROS_FACTORY_PRIVATE_KEY",
    "GH_TOKEN",
    "GITHUB_TOKEN",
}

_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_GIT_OID_RE = re.compile(
    r"^(?:[0-9a-f]{40}|[0-9a-f]{64})$"
)


class SignedAuthoringHardeningError(RuntimeError):
    """Fail-closed hardened authoring failure."""


class StaleAuthoringOperation(
    SignedAuthoringHardeningError
):
    """Authoritative base moved; revalidation required."""


class PublishAmbiguous(
    SignedAuthoringHardeningError
):
    """Privileged write could not be reconciled safely."""


@dataclass(frozen=True, slots=True)
class AuthoringManifest:
    """Immutable validated-authoring contract."""

    schema_version: str
    operation_id: str
    operation: str
    repository: str
    base_branch: str
    target_branch: str
    expected_head_sha: str
    tree_digest: str
    files: tuple[tuple[str, str], ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "operation_id": self.operation_id,
            "operation": self.operation,
            "repository": self.repository,
            "base_branch": self.base_branch,
            "target_branch": self.target_branch,
            "expected_head_sha": (
                self.expected_head_sha
            ),
            "tree_digest": self.tree_digest,
            "files": [
                {
                    "path": path,
                    "sha256": digest,
                }
                for path, digest in self.files
            ],
        }

    @classmethod
    def from_dict(
        cls,
        payload: Mapping[str, Any],
    ) -> AuthoringManifest:
        expected_keys = {
            "schema_version",
            "operation_id",
            "operation",
            "repository",
            "base_branch",
            "target_branch",
            "expected_head_sha",
            "tree_digest",
            "files",
        }

        require(
            set(payload) == expected_keys,
            (
                "manifest keys do not match "
                "the canonical schema"
            ),
        )

        files_raw = payload.get("files")

        if not isinstance(files_raw, list):
            raise SignedAuthoringHardeningError(
                "manifest files must be a list"
            )

        files: list[tuple[str, str]] = []

        for item in files_raw:
            require(
                isinstance(item, dict)
                and set(item)
                == {"path", "sha256"},
                "manifest file entry is invalid",
            )

            path = item.get("path")
            digest = item.get("sha256")

            require(
                isinstance(path, str)
                and bool(path)
                and isinstance(digest, str)
                and _SHA256_RE.fullmatch(digest)
                is not None,
                "manifest file entry is invalid",
            )

            files.append((path, digest))

        scalar_names = expected_keys - {"files"}

        for name in scalar_names:
            value = payload.get(name)

            require(
                isinstance(value, str)
                and bool(value),
                (
                    "manifest field is invalid: "
                    f"{name}"
                ),
            )

        manifest = cls(
            schema_version=str(
                payload["schema_version"]
            ),
            operation_id=str(
                payload["operation_id"]
            ),
            operation=str(
                payload["operation"]
            ),
            repository=str(
                payload["repository"]
            ),
            base_branch=str(
                payload["base_branch"]
            ),
            target_branch=str(
                payload["target_branch"]
            ),
            expected_head_sha=str(
                payload["expected_head_sha"]
            ),
            tree_digest=str(
                payload["tree_digest"]
            ),
            files=tuple(files),
        )

        manifest.validate()

        return manifest

    def validate(self) -> None:
        require(
            self.schema_version
            == MANIFEST_SCHEMA,
            "unsupported manifest schema",
        )

        require(
            self.operation == OPERATION,
            "unsupported authoring operation",
        )

        require(
            self.repository.count("/") == 1
            and all(
                self.repository.split("/", 1)
            ),
            "manifest repository is invalid",
        )

        require(
            self.base_branch == MAIN_BRANCH,
            (
                "authoring base branch "
                "must be main"
            ),
        )

        require(
            self.target_branch
            == TARGET_BRANCH,
            (
                "authoring target branch "
                "is outside operation scope"
            ),
        )

        require(
            self.target_branch
            != MAIN_BRANCH,
            "direct main publication is forbidden",
        )

        require(
            _GIT_OID_RE.fullmatch(
                self.expected_head_sha
            )
            is not None,
            "expected_head_sha is invalid",
        )

        require(
            _SHA256_RE.fullmatch(
                self.tree_digest
            )
            is not None,
            "tree_digest must be SHA-256",
        )

        paths = [
            path
            for path, _ in self.files
        ]

        require(
            len(paths) == len(set(paths)),
            (
                "manifest contains "
                "duplicate file paths"
            ),
        )

        require(
            set(paths) == ALLOWED_PATHS,
            (
                "manifest paths do not match "
                "operation allowlist"
            ),
        )

        for path, digest in self.files:
            require(
                _SHA256_RE.fullmatch(
                    digest
                )
                is not None,
                (
                    "manifest digest "
                    f"is invalid: {path}"
                ),
            )

        expected_operation_id = (
            operation_identity(
                repository=self.repository,
                base_branch=self.base_branch,
                target_branch=(
                    self.target_branch
                ),
                expected_head_sha=(
                    self.expected_head_sha
                ),
                tree_digest=(
                    self.tree_digest
                ),
                files=self.files,
            )
        )

        require(
            self.operation_id
            == expected_operation_id,
            (
                "manifest operation_id "
                "does not match immutable inputs"
            ),
        )


def require(
    condition: bool,
    message: str,
) -> None:
    """Raise fail-closed authoring error."""

    if not condition:
        raise SignedAuthoringHardeningError(
            message
        )


def sha256_text(text: str) -> str:
    """SHA-256 exact UTF-8 text bytes."""

    return hashlib.sha256(
        text.encode("utf-8")
    ).hexdigest()


def canonical_tree_digest(
    contents: Mapping[str, str],
) -> str:
    """Digest exact path/content publication tree."""

    digest = hashlib.sha256()

    for path in sorted(contents):
        digest.update(
            path.encode("utf-8")
        )
        digest.update(b"\0")
        digest.update(
            contents[path].encode("utf-8")
        )
        digest.update(b"\0")

    return digest.hexdigest()


def operation_identity(
    *,
    repository: str,
    base_branch: str,
    target_branch: str,
    expected_head_sha: str,
    tree_digest: str,
    files: tuple[tuple[str, str], ...],
) -> str:
    """Deterministic idempotency key."""

    payload = {
        "schema_version": MANIFEST_SCHEMA,
        "operation": OPERATION,
        "repository": repository,
        "base_branch": base_branch,
        "target_branch": target_branch,
        "expected_head_sha": (
            expected_head_sha
        ),
        "tree_digest": tree_digest,
        "files": [
            {
                "path": path,
                "sha256": digest,
            }
            for path, digest
            in sorted(files)
        ],
    }

    raw = json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    ).encode("utf-8")

    return (
        "case-testy-author-"
        + hashlib.sha256(
            raw
        ).hexdigest()[:24]
    )


def validation_environment(
    source: Mapping[str, str] | None = None,
) -> dict[str, str]:
    """Return environment without write/signing secrets."""

    env = dict(
        os.environ
        if source is None
        else source
    )

    for key in _SECRET_ENV_KEYS:
        env.pop(key, None)

    return env


def run_command(
    command: list[str],
    *,
    cwd: Path,
    env: Mapping[str, str] | None = None,
) -> str:
    """Run deterministic validation command."""

    result = subprocess.run(
        command,
        cwd=cwd,
        env=(
            None
            if env is None
            else dict(env)
        ),
        capture_output=True,
        text=True,
        check=False,
    )

    if result.returncode != 0:
        output = "\n".join(
            part.strip()
            for part
            in (
                result.stdout,
                result.stderr,
            )
            if part.strip()
        )

        raise SignedAuthoringHardeningError(
            (
                "command failed "
                f"({result.returncode}): "
                f"{' '.join(command)}"
            )
            + (
                f"\n{output}"
                if output
                else ""
            )
        )

    return result.stdout.strip()


def git_head(
    repo_root: Path,
) -> str:
    """Read checkout HEAD."""

    head = run_command(
        [
            "git",
            "rev-parse",
            "HEAD",
        ],
        cwd=repo_root,
        env=validation_environment(),
    )

    require(
        _GIT_OID_RE.fullmatch(head)
        is not None,
        (
            "git returned "
            f"an invalid HEAD: {head!r}"
        ),
    )

    return head


def working_tree_paths(
    repo_root: Path,
) -> set[str]:
    """Return tracked and untracked changed paths."""

    tracked = run_command(
        [
            "git",
            "diff",
            "--name-only",
            "--",
        ],
        cwd=repo_root,
        env=validation_environment(),
    )

    untracked = run_command(
        [
            "git",
            "ls-files",
            "--others",
            "--exclude-standard",
        ],
        cwd=repo_root,
        env=validation_environment(),
    )

    return {
        line.strip()
        for block
        in (
            tracked,
            untracked,
        )
        for line
        in block.splitlines()
        if line.strip()
    }


def prepare_operation(
    *,
    repo_root: Path,
    manifest_path: Path,
) -> AuthoringManifest:
    """Render and validate exact bytes without signing secrets."""

    repository = os.environ.get(
        "GITHUB_REPOSITORY",
        "",
    ).strip()

    expected_head = os.environ.get(
        "GITHUB_SHA",
        "",
    ).strip()

    require(
        repository.count("/") == 1
        and all(
            repository.split("/", 1)
        ),
        (
            "GITHUB_REPOSITORY "
            "is missing or invalid"
        ),
    )

    require(
        _GIT_OID_RE.fullmatch(
            expected_head
        )
        is not None,
        (
            "GITHUB_SHA "
            "is missing or invalid"
        ),
    )

    require(
        not working_tree_paths(
            repo_root
        ),
        (
            "checkout must be clean "
            "before preparation"
        ),
    )

    require(
        git_head(repo_root)
        == expected_head,
        (
            "checkout HEAD does not "
            "match GITHUB_SHA"
        ),
    )

    source_path = (
        repo_root
        / SOURCE_PATH
    )

    test_path = (
        repo_root
        / TEST_PATH
    )

    require(
        source_path.is_file(),
        (
            "canonical regression-suite "
            "module is missing"
        ),
    )

    require(
        not test_path.exists(),
        (
            "manual inventory regression "
            "test already exists"
        ),
    )

    original = source_path.read_text(
        encoding="utf-8"
    )

    updated = (
        render_regression_suite_update(
            original
        )
    )

    test_content = render_test_file()

    source_path.write_text(
        updated,
        encoding="utf-8",
    )

    test_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    test_path.write_text(
        test_content,
        encoding="utf-8",
    )

    require(
        working_tree_paths(
            repo_root
        )
        == ALLOWED_PATHS,
        (
            "unexpected working-tree "
            "scope after rendering"
        ),
    )

    safe_env = validation_environment()

    run_command(
        [
            "uv",
            "run",
            "--frozen",
            "--extra",
            "dev",
            "pytest",
            TEST_PATH,
            "-q",
        ],
        cwd=repo_root,
        env=safe_env,
    )

    run_command(
        [
            "uv",
            "run",
            "--frozen",
            "--extra",
            "dev",
            "python",
            "-m",
            (
                "factory.quality."
                "case_regression_suite"
            ),
            "--validate-only",
        ],
        cwd=repo_root,
        env=safe_env,
    )

    require(
        git_head(repo_root)
        == expected_head,
        (
            "checkout HEAD changed "
            "during validation"
        ),
    )

    require(
        working_tree_paths(
            repo_root
        )
        == ALLOWED_PATHS,
        (
            "validated working-tree "
            "scope changed unexpectedly"
        ),
    )

    contents = {
        path: (
            repo_root
            / path
        ).read_text(
            encoding="utf-8"
        )
        for path
        in sorted(ALLOWED_PATHS)
    }

    files = tuple(
        (
            path,
            sha256_text(
                contents[path]
            ),
        )
        for path
        in sorted(contents)
    )

    tree_digest = (
        canonical_tree_digest(
            contents
        )
    )

    operation_id = operation_identity(
        repository=repository,
        base_branch=MAIN_BRANCH,
        target_branch=TARGET_BRANCH,
        expected_head_sha=(
            expected_head
        ),
        tree_digest=tree_digest,
        files=files,
    )

    manifest = AuthoringManifest(
        schema_version=(
            MANIFEST_SCHEMA
        ),
        operation_id=operation_id,
        operation=OPERATION,
        repository=repository,
        base_branch=MAIN_BRANCH,
        target_branch=TARGET_BRANCH,
        expected_head_sha=(
            expected_head
        ),
        tree_digest=tree_digest,
        files=files,
    )

    manifest.validate()

    manifest_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    manifest_path.write_text(
        json.dumps(
            manifest.to_dict(),
            sort_keys=True,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    print(
        json.dumps(
            {
                "status": "VALIDATED",
                "operation_id": (
                    manifest.operation_id
                ),
                "expected_head_sha": (
                    manifest.expected_head_sha
                ),
                "tree_digest": (
                    manifest.tree_digest
                ),
            },
            sort_keys=True,
        )
    )

    return manifest


def load_manifest(
    manifest_path: Path,
) -> AuthoringManifest:
    """Load and structurally validate manifest."""

    try:
        payload = json.loads(
            manifest_path.read_text(
                encoding="utf-8"
            )
        )
    except (
        OSError,
        json.JSONDecodeError,
    ) as exc:
        raise SignedAuthoringHardeningError(
            "authoring manifest "
            "cannot be read"
        ) from exc

    require(
        isinstance(payload, dict),
        (
            "authoring manifest "
            "must be an object"
        ),
    )

    return AuthoringManifest.from_dict(
        payload
    )


def read_validated_contents(
    *,
    repo_root: Path,
    manifest: AuthoringManifest,
) -> dict[str, str]:
    """Verify tested bytes are still exact publish bytes."""

    contents: dict[str, str] = {}

    for (
        path,
        expected_digest,
    ) in manifest.files:
        file_path = (
            repo_root
            / path
        )

        require(
            file_path.is_file()
            and not file_path.is_symlink(),
            (
                "validated file is "
                f"missing or unsafe: {path}"
            ),
        )

        text = file_path.read_text(
            encoding="utf-8"
        )

        require(
            sha256_text(text)
            == expected_digest,
            (
                "validated bytes changed "
                f"before publish: {path}"
            ),
        )

        contents[path] = text

    require(
        canonical_tree_digest(
            contents
        )
        == manifest.tree_digest,
        (
            "validated tree digest "
            "changed before publish"
        ),
    )

    require(
        working_tree_paths(
            repo_root
        )
        == ALLOWED_PATHS,
        (
            "working-tree scope changed "
            "before publish"
        ),
    )

    require(
        git_head(repo_root)
        == manifest.expected_head_sha,
        (
            "checkout HEAD changed "
            "before publish"
        ),
    )

    return contents


def branch_head(
    client: GitHubActionsClient,
    branch: str,
) -> str | None:
    """Return branch SHA; only true 404 maps to None."""

    ref = client.get_ref_or_none(
        branch
    )

    if ref is None:
        return None

    obj = ref.get("object")

    if not isinstance(obj, dict):
        raise SignedAuthoringHardeningError(
            "GitHub ref response has no object"
        )

    sha = obj.get("sha")

    require(
        isinstance(sha, str)
        and _GIT_OID_RE.fullmatch(
            sha
        )
        is not None,
        (
            "GitHub ref response "
            "has invalid SHA"
        ),
    )

    return sha


def remote_text_file(
    client: GitHubActionsClient,
    *,
    path: str,
    ref: str,
) -> str:
    """Read exact UTF-8 file bytes from one Git revision."""

    encoded_path = "/".join(
        urllib.parse.quote(
            part,
            safe="",
        )
        for part
        in path.split("/")
    )

    encoded_ref = urllib.parse.quote(
        ref,
        safe="",
    )

    payload = client._api(
        "GET",
        (
            f"/repos/{client.repository}"
            f"/contents/{encoded_path}"
            f"?ref={encoded_ref}"
        ),
    )

    require(
        payload.get("type") == "file",
        (
            "remote path "
            f"is not a file: {path}"
        ),
    )

    content = payload.get("content")
    encoding = payload.get("encoding")

    if not isinstance(content, str) or encoding != "base64":
        raise SignedAuthoringHardeningError(
            "remote file encoding "
            f"is invalid: {path}"
        )

    try:
        raw = base64.b64decode(
            content
        )

        return raw.decode("utf-8")

    except (
        ValueError,
        UnicodeDecodeError,
    ) as exc:
        raise PublishAmbiguous(
            "remote file "
            f"cannot be decoded: {path}"
        ) from exc


def verify_published_commit(
    *,
    client: GitHubActionsClient,
    manifest: AuthoringManifest,
    resulting_sha: str,
) -> None:
    """Post-write verification of commit, ref and bytes."""

    require(
        _GIT_OID_RE.fullmatch(
            resulting_sha
        )
        is not None,
        (
            "resulting publication "
            "SHA is invalid"
        ),
    )

    commit = client.get_commit(
        resulting_sha
    )

    commit_body = commit.get(
        "commit"
    )

    require(
        isinstance(
            commit_body,
            dict,
        ),
        (
            "published commit "
            "payload is invalid"
        ),
    )

    verification = commit_body.get(
        "verification"
    )

    require(
        isinstance(
            verification,
            dict,
        )
        and verification.get(
            "verified"
        )
        is True
        and verification.get(
            "reason"
        )
        == "valid",
        (
            "published commit signature "
            "is not verified: "
            f"{resulting_sha}"
        ),
    )

    parents = commit.get(
        "parents"
    )

    require(
        isinstance(
            parents,
            list,
        )
        and len(parents) == 1,
        (
            "published commit must "
            "have exactly one parent"
        ),
    )

    parent = parents[0]

    require(
        isinstance(parent, dict)
        and parent.get("sha")
        == manifest.expected_head_sha,
        (
            "published commit parent "
            "does not match expected head"
        ),
    )

    message = commit_body.get(
        "message"
    )

    require(
        isinstance(message, str)
        and manifest.operation_id
        in message,
        (
            "published commit is not "
            "bound to operation_id"
        ),
    )

    require(
        branch_head(
            client,
            manifest.target_branch,
        )
        == resulting_sha,
        (
            "target branch head "
            "does not match resulting commit"
        ),
    )

    compare = client.compare_commits(
        manifest.expected_head_sha,
        resulting_sha,
    )

    files = compare.get(
        "files"
    )

    require(
        isinstance(files, list),
        (
            "GitHub compare returned "
            "invalid files"
        ),
    )

    remote_paths = {
        item.get("filename")
        for item in files
        if isinstance(item, dict)
        and isinstance(
            item.get("filename"),
            str,
        )
    }

    require(
        remote_paths == ALLOWED_PATHS,
        (
            "unexpected remote diff: "
            f"{sorted(remote_paths)}"
        ),
    )

    require(
        compare.get("ahead_by") == 1
        and compare.get(
            "total_commits"
        )
        == 1,
        (
            "publication must be "
            "exactly one commit ahead"
        ),
    )

    remote_contents = {
        path: remote_text_file(
            client,
            path=path,
            ref=resulting_sha,
        )
        for path
        in sorted(ALLOWED_PATHS)
    }

    for (
        path,
        expected_digest,
    ) in manifest.files:
        require(
            sha256_text(
                remote_contents[path]
            )
            == expected_digest,
            (
                "published content "
                f"digest mismatch: {path}"
            ),
        )

    require(
        canonical_tree_digest(
            remote_contents
        )
        == manifest.tree_digest,
        (
            "published tree digest "
            "does not match validated tree"
        ),
    )


def reconcile_existing_publish(
    *,
    client: GitHubActionsClient,
    manifest: AuthoringManifest,
    candidate_sha: str | None,
) -> str | None:
    """Recognize only an already verified identical operation."""

    if (
        candidate_sha is None
        or candidate_sha
        == manifest.expected_head_sha
    ):
        return None

    try:
        verify_published_commit(
            client=client,
            manifest=manifest,
            resulting_sha=candidate_sha,
        )
    except (
        GitHubActionsError,
        SignedAuthoringHardeningError,
    ):
        return None

    return candidate_sha


def ensure_target_branch(
    *,
    client: GitHubActionsClient,
    manifest: AuthoringManifest,
) -> str | None:
    """Create target ref or reconcile exact prior publication."""

    current = branch_head(
        client,
        manifest.target_branch,
    )

    reconciled = (
        reconcile_existing_publish(
            client=client,
            manifest=manifest,
            candidate_sha=current,
        )
    )

    if reconciled is not None:
        return reconciled

    if current is not None:
        require(
            current
            == manifest.expected_head_sha,
            (
                "target branch exists at "
                "an unexpected revision and "
                "does not match this operation"
            ),
        )

        return None

    try:
        client.create_ref(
            manifest.target_branch,
            manifest.expected_head_sha,
        )

    except GitHubActionsError as exc:
        observed = branch_head(
            client,
            manifest.target_branch,
        )

        if (
            observed
            != manifest.expected_head_sha
        ):
            raise PublishAmbiguous(
                "target branch creation "
                "failed and could not "
                "be reconciled"
            ) from exc

    require(
        branch_head(
            client,
            manifest.target_branch,
        )
        == manifest.expected_head_sha,
        (
            "target branch creation "
            "did not converge"
        ),
    )

    return None


def publish_atomic_commit(
    *,
    client: GitHubActionsClient,
    manifest: AuthoringManifest,
    contents: Mapping[str, str],
) -> str:
    """Publish all validated files as one CAS-bound commit."""

    live_base = client.get_ref_sha(
        manifest.base_branch
    )

    if (
        live_base
        != manifest.expected_head_sha
    ):
        raise StaleAuthoringOperation(
            "base moved before "
            "atomic publication: "
            f"expected="
            f"{manifest.expected_head_sha} "
            f"live={live_base}"
        )

    message_body = (
        "LUKART-Operation-ID: "
        f"{manifest.operation_id}\n"
        "Validated-Tree-SHA256: "
        f"{manifest.tree_digest}\n"
        "Expected-Base: "
        f"{manifest.expected_head_sha}"
    )

    try:
        result = (
            client.create_commit_on_branch(
                branch=(
                    manifest.target_branch
                ),
                expected_head_oid=(
                    manifest.expected_head_sha
                ),
                message_headline=(
                    "case-testy: atomically "
                    "validate manual smoke inventory"
                ),
                message_body=message_body,
                additions=dict(contents),
                operation_id=(
                    manifest.operation_id
                ),
            )
        )

        resulting_sha = (
            result.commit_oid
        )

    except GitHubActionsError as exc:
        candidate = branch_head(
            client,
            manifest.target_branch,
        )

        reconciled = (
            reconcile_existing_publish(
                client=client,
                manifest=manifest,
                candidate_sha=candidate,
            )
        )

        if reconciled is None:
            raise PublishAmbiguous(
                "atomic publication failed "
                "and could not be reconciled"
            ) from exc

        resulting_sha = reconciled

    verify_published_commit(
        client=client,
        manifest=manifest,
        resulting_sha=resulting_sha,
    )

    live_after = client.get_ref_sha(
        manifest.base_branch
    )

    if (
        live_after
        != manifest.expected_head_sha
    ):
        raise StaleAuthoringOperation(
            "base moved during publication; "
            "verified candidate "
            f"{resulting_sha} remains "
            "isolated and requires "
            "revalidation"
        )

    return resulting_sha


def ensure_pull_request(
    *,
    client: GitHubActionsClient,
    manifest: AuthoringManifest,
    resulting_sha: str,
) -> dict[str, Any]:
    """Return or create exactly one bounded PR."""

    pulls = (
        client.list_open_pull_requests(
            head_branch=(
                manifest.target_branch
            ),
            base_branch=(
                manifest.base_branch
            ),
        )
    )

    require(
        len(pulls) <= 1,
        (
            "multiple open PRs exist "
            "for target branch"
        ),
    )

    if pulls:
        pr = pulls[0]

    else:
        body = (
            PR_BODY.rstrip()
            + "\n\n"
            + (
                "Operation-ID: "
                f"`{manifest.operation_id}`\n"
            )
            + (
                "Validated tree: "
                f"`{manifest.tree_digest}`\n"
            )
            + (
                "Expected base: "
                f"`{manifest.expected_head_sha}`\n"
            )
        )

        try:
            pr = (
                client.create_pull_request(
                    title=PR_TITLE,
                    head=(
                        manifest.target_branch
                    ),
                    base=(
                        manifest.base_branch
                    ),
                    body=body,
                )
            )

        except GitHubActionsError as exc:
            reconciled = (
                client.list_open_pull_requests(
                    head_branch=(
                        manifest.target_branch
                    ),
                    base_branch=(
                        manifest.base_branch
                    ),
                )
            )

            if len(reconciled) != 1:
                raise PublishAmbiguous(
                    "PR creation failed "
                    "and could not be reconciled"
                ) from exc

            pr = reconciled[0]

    number = pr.get(
        "number"
    )

    url = pr.get(
        "html_url"
    )

    head = pr.get(
        "head"
    )

    base = pr.get(
        "base"
    )

    require(
        isinstance(number, int)
        and number > 0,
        (
            "GitHub returned "
            "invalid PR number"
        ),
    )

    require(
        isinstance(url, str)
        and bool(url),
        (
            "GitHub returned "
            "invalid PR URL"
        ),
    )

    require(
        isinstance(head, dict)
        and head.get("ref")
        == manifest.target_branch
        and head.get("sha")
        == resulting_sha,
        (
            "PR head does not match "
            "resulting commit"
        ),
    )

    require(
        isinstance(base, dict)
        and base.get("ref")
        == manifest.base_branch,
        (
            "PR base does not "
            "match manifest"
        ),
    )

    return pr


def publish_operation(
    *,
    repo_root: Path,
    manifest_path: Path,
    client: GitHubActionsClient | None = None,
) -> dict[str, Any]:
    """Perform bounded privileged publication."""

    manifest = load_manifest(
        manifest_path
    )

    contents = (
        read_validated_contents(
            repo_root=repo_root,
            manifest=manifest,
        )
    )

    repository_env = os.environ.get(
        "GITHUB_REPOSITORY",
        "",
    ).strip()

    require(
        repository_env
        == manifest.repository,
        (
            "repository identity "
            "does not match manifest"
        ),
    )

    effective_client = (
        client
        or GitHubActionsClient.from_environment()
    )

    require(
        effective_client.repository
        == manifest.repository,
        (
            "publisher repository "
            "identity mismatch"
        ),
    )

    live_base = (
        effective_client.get_ref_sha(
            manifest.base_branch
        )
    )

    if (
        live_base
        != manifest.expected_head_sha
    ):
        raise StaleAuthoringOperation(
            "base moved before publication: "
            f"expected="
            f"{manifest.expected_head_sha} "
            f"live={live_base}"
        )

    reconciled = ensure_target_branch(
        client=effective_client,
        manifest=manifest,
    )

    if reconciled is None:
        resulting_sha = (
            publish_atomic_commit(
                client=effective_client,
                manifest=manifest,
                contents=contents,
            )
        )
    else:
        resulting_sha = reconciled

    verify_published_commit(
        client=effective_client,
        manifest=manifest,
        resulting_sha=resulting_sha,
    )

    require(
        effective_client.get_ref_sha(
            manifest.base_branch
        )
        == manifest.expected_head_sha,
        (
            "base moved before PR publication; "
            "revalidation required"
        ),
    )

    pr = ensure_pull_request(
        client=effective_client,
        manifest=manifest,
        resulting_sha=resulting_sha,
    )

    receipt = {
        "schema_version": RECEIPT_SCHEMA,
        "operation_id": (
            manifest.operation_id
        ),
        "operation": (
            manifest.operation
        ),
        "repository": (
            manifest.repository
        ),
        "input_sha": (
            manifest.expected_head_sha
        ),
        "tree_digest": (
            manifest.tree_digest
        ),
        "resulting_sha": resulting_sha,
        "changed_paths": sorted(
            ALLOWED_PATHS
        ),
        "pr_number": pr["number"],
        "pr_url": pr["html_url"],
        "publication": "VERIFIED",
        "signature": "VERIFIED",
        "ci": "PENDING_EXACT_SHA",
    }

    print(
        json.dumps(
            receipt,
            sort_keys=True,
        )
    )

    return receipt


def build_parser() -> argparse.ArgumentParser:
    """Build prepare/publish CLI."""

    parser = argparse.ArgumentParser(
        description=(
            "Prepare or publish one hardened "
            "CASE-TESTY signed-authoring operation."
        )
    )

    subparsers = parser.add_subparsers(
        dest="command",
        required=True,
    )

    for name in (
        "prepare",
        "publish",
    ):
        subparser = (
            subparsers.add_parser(
                name
            )
        )

        subparser.add_argument(
            "--manifest",
            required=True,
            type=Path,
        )

    return parser


def main(
    argv: list[str] | None = None,
) -> int:
    """CLI entrypoint."""

    args = (
        build_parser().parse_args(
            argv
        )
    )

    if args.command == "prepare":
        prepare_operation(
            repo_root=Path.cwd(),
            manifest_path=args.manifest,
        )

    elif args.command == "publish":
        publish_operation(
            repo_root=Path.cwd(),
            manifest_path=args.manifest,
        )

    else:
        raise SignedAuthoringHardeningError(
            "unsupported command"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())