"""
Human-readable run note written next to case file notes/.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path


def write_run_note(
    *,
    notes_dir: Path,
    case_key: str,
    graph_case_id: str,
    fact_ok: bool | None,
    law_ok: bool | None,
    review_ok: bool | None,
    snapshot_path: Path | None,
    snapshot_status: str | None,
    outbound_files: list[Path] | None = None,
    dossier_txt: Path | None = None,
    dossier_docx: Path | None = None,
) -> Path:
    notes_dir = Path(notes_dir)
    notes_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        f"# Last run — {case_key}",
        "",
        f"- Time: {stamp}",
        f"- Graph case id: `{graph_case_id}`",
        f"- FactAgent: {_flag(fact_ok)}",
        f"- LawAgent: {_flag(law_ok)}",
        f"- ReviewAgent: {_flag(review_ok)}",
        f"- Snapshot status: `{snapshot_status or 'n/a'}`",
    ]
    if snapshot_path is not None:
        lines.append(f"- Snapshot file: `{snapshot_path}`")
    if dossier_txt is not None:
        lines.append(f"- Dossier TXT: `{dossier_txt}`")
    if dossier_docx is not None:
        lines.append(f"- Dossier DOCX: `{dossier_docx}`")
    if outbound_files:
        lines.append("- Outbound copies:")
        for p in outbound_files:
            lines.append(f"  - `{p}`")
    lines.append("")
    lines.append("Generated by LukArt CaseWorkspace.")
    lines.append("")

    path = notes_dir / "last_run.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path.resolve()


def _flag(value: bool | None) -> str:
    if value is True:
        return "PASS"
    if value is False:
        return "FAIL"
    return "n/a"