"""P2 semantic intelligence and bounded runtime contracts."""

from core.p2.quality import (
    ExplainabilityReport,
    FailureEvent,
    FailureSeverity,
    GoldCandidate,
    MetricDirection,
    MetricTrend,
    QualityObservation,
    QualityTrendAnalyzer,
    TrendStatus,
    discover_gold_candidates,
    explain_result,
)
from core.p2.runtime import (
    AgentProvider,
    AgentResult,
    AgentTask,
    ApiEnvelope,
    BoundedAgentRuntime,
    ExecutionBudget,
    LruArtifactCache,
    Plugin,
    PluginRegistry,
    RuntimeContractError,
    bounded_parallel_map,
)
from core.p2.semantic import (
    DependencyGraph,
    ReplayComparison,
    ReplaySnapshot,
    SemanticChange,
    SemanticDiff,
    SemanticSeverity,
    compare_replays,
    digest,
    semantic_diff,
)

__all__ = [
    "AgentProvider",
    "AgentResult",
    "AgentTask",
    "ApiEnvelope",
    "BoundedAgentRuntime",
    "DependencyGraph",
    "ExecutionBudget",
    "ExplainabilityReport",
    "FailureEvent",
    "FailureSeverity",
    "GoldCandidate",
    "LruArtifactCache",
    "MetricDirection",
    "MetricTrend",
    "Plugin",
    "PluginRegistry",
    "QualityObservation",
    "QualityTrendAnalyzer",
    "ReplayComparison",
    "ReplaySnapshot",
    "RuntimeContractError",
    "SemanticChange",
    "SemanticDiff",
    "SemanticSeverity",
    "TrendStatus",
    "bounded_parallel_map",
    "compare_replays",
    "digest",
    "discover_gold_candidates",
    "explain_result",
    "semantic_diff",
]
